# Generated by Django 5.2.17 on 2026-10-01 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='به\u200cروزرسانی')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='زیرعنوان')),
                ('image', models.ImageField(upload_to='slides/', verbose_name='تصویر')),
                ('link_url', models.CharField(blank=True, help_text='مثلا /p/12 یا یک آدرس خارجی', max_length=300, verbose_name='لینک مقصد')),
                ('link_label', models.CharField(blank=True, default='مشاهده', max_length=50, verbose_name='متن دکمه')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'اسلاید',
                'verbose_name_plural': 'اسلایدهای صفحه اصلی',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
