# Generated by Django 5.2.17 on 2026-10-02 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orgs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='به\u200cروزرسانی')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='عنوان')),
                ('icon', models.CharField(blank=True, max_length=40, verbose_name='آیکن')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب')),
            ],
            options={
                'verbose_name': 'دسته محصولات فروشگاهی',
                'verbose_name_plural': 'دسته\u200cهای محصولات فروشگاهی',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ShopProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='به\u200cروزرسانی')),
                ('name', models.CharField(max_length=200, verbose_name='نام محصول')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('image', models.ImageField(blank=True, upload_to='shop/%Y/%m/', verbose_name='تصویر')),
                ('price', models.PositiveBigIntegerField(verbose_name='قیمت (ریال)')),
                ('old_price', models.PositiveBigIntegerField(blank=True, help_text='در صورت تکمیل، به\u200cصورت خط\u200cخورده و با درصد تخفیف نمایش داده می\u200cشود', null=True, verbose_name='قیمت پیش از تخفیف (ریال)')),
                ('unit', models.CharField(choices=[('piece', 'عدد'), ('kg', 'کیلوگرم'), ('g', 'گرم'), ('pack', 'بسته'), ('l', 'لیتر'), ('m', 'متر'), ('service', 'خدمت')], default='piece', max_length=10, verbose_name='واحد')),
                ('brand', models.CharField(blank=True, max_length=120, verbose_name='برند/تولیدکننده')),
                ('is_available', models.BooleanField(db_index=True, default=True, verbose_name='موجود')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='نمایش در فروشگاه')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='shop.shopcategory', verbose_name='دسته')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_products', to='orgs.store', verbose_name='فروشگاه')),
            ],
            options={
                'verbose_name': 'محصول فروشگاه',
                'verbose_name_plural': 'محصولات فروشگاه\u200cها',
                'ordering': ['order', '-created_at'],
                'indexes': [models.Index(fields=['store', 'is_active', 'is_available'], name='shop_shoppr_store_i_34edce_idx')],
            },
        ),
    ]
