# Generated by Django 5.2.17 on 2026-10-03 20:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0001_initial'),
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='به\u200cروزرسانی')),
                ('code', models.CharField(max_length=12, unique=True, verbose_name='کد سفارش')),
                ('customer_name', models.CharField(max_length=120, verbose_name='نام مشتری')),
                ('customer_phone', models.CharField(max_length=15, verbose_name='تلفن تماس')),
                ('delivery', models.CharField(choices=[('pickup', 'دریافت حضوری از فروشگاه'), ('delivery', 'ارسال به نشانی مشتری')], default='pickup', max_length=10, verbose_name='نحوه تحویل')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='نشانی تحویل')),
                ('note', models.TextField(blank=True, verbose_name='توضیحات مشتری')),
                ('total', models.PositiveBigIntegerField(default=0, verbose_name='مبلغ کل (ریال)')),
                ('status', models.CharField(choices=[('new', 'ثبت شده'), ('confirmed', 'تایید فروشگاه'), ('preparing', 'در حال آماده\u200cسازی'), ('ready', 'آماده تحویل'), ('delivered', 'تحویل شد'), ('canceled', 'لغو شد')], db_index=True, default='new', max_length=10, verbose_name='وضعیت')),
                ('store_note', models.TextField(blank=True, verbose_name='پاسخ/یادداشت فروشگاه')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان بسته شدن')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='مشتری')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='orgs.store', verbose_name='فروشگاه')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارش\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'ثبت شده'), ('confirmed', 'تایید فروشگاه'), ('preparing', 'در حال آماده\u200cسازی'), ('ready', 'آماده تحویل'), ('delivered', 'تحویل شد'), ('canceled', 'لغو شد')], max_length=10)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='shop.order')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام کالا')),
                ('unit_display', models.CharField(blank=True, max_length=30, verbose_name='واحد')),
                ('price', models.PositiveBigIntegerField(verbose_name='قیمت واحد (ریال)')),
                ('quantity', models.PositiveSmallIntegerField(default=1, verbose_name='تعداد')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='shop.shopproduct')),
            ],
            options={
                'verbose_name': 'قلم سفارش',
                'verbose_name_plural': 'اقلام سفارش',
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['store', 'status'], name='shop_order_store_i_d8ca9b_idx'),
        ),
    ]
