# Generated by Django 5.2.17 on 2026-10-08 06:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def approve_existing(apps, schema_editor):
    """محصولاتی که پیش از این گردش تایید ثبت شده‌اند، تاییدشده در نظر گرفته می‌شوند
    تا با اجرای مهاجرت ناگهان از ویترین فروشگاه‌ها حذف نشوند."""
    apps.get_model("shop", "ShopProduct").objects.update(status="approved")


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0001_initial'),
        ('shop', '0002_order_orderevent_orderitem_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='shopproduct',
            name='shop_shoppr_store_i_34edce_idx',
        ),
        migrations.AddField(
            model_name='shopproduct',
            name='review_note',
            field=models.CharField(blank=True, max_length=300, verbose_name='توضیح بررسی'),
        ),
        migrations.AddField(
            model_name='shopproduct',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان بررسی'),
        ),
        migrations.AddField(
            model_name='shopproduct',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='بررسی\u200cکننده'),
        ),
        migrations.AddField(
            model_name='shopproduct',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار تایید صمت'), ('approved', 'تاییدشده'), ('rejected', 'رد شده')], db_index=True, default='pending', max_length=10, verbose_name='وضعیت تایید'),
        ),
        migrations.AddIndex(
            model_name='shopproduct',
            index=models.Index(fields=['store', 'is_active', 'is_available', 'status'], name='shop_shoppr_store_i_32a0e1_idx'),
        ),
        migrations.RunPython(approve_existing, migrations.RunPython.noop),
    ]
