# Generated by Django 5.2.17 on 2026-09-24 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='به\u200cروزرسانی')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('supplier', models.CharField(blank=True, max_length=200, verbose_name='تامین\u200cکننده/واردکننده')),
                ('total_quantity', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='مقدار کل')),
                ('unit', models.CharField(default='کیلوگرم', max_length=20, verbose_name='واحد')),
                ('allocation_price', models.PositiveBigIntegerField(verbose_name='قیمت تخصیص (ریال/واحد)')),
                ('consumer_price', models.PositiveBigIntegerField(verbose_name='سقف قیمت مصرف\u200cکننده (ریال/واحد)')),
                ('starts_on', models.DateField(verbose_name='شروع توزیع')),
                ('ends_on', models.DateField(blank=True, null=True, verbose_name='پایان توزیع')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('active', 'در حال توزیع'), ('closed', 'بسته شده')], default='draft', max_length=10, verbose_name='وضعیت')),
                ('note', models.TextField(blank=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'تخصیص',
                'verbose_name_plural': 'تخصیص\u200cها',
                'ordering': ['-starts_on', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='AllocationShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='به\u200cروزرسانی')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='مقدار')),
            ],
            options={
                'verbose_name': 'سهم اتحادیه',
                'verbose_name_plural': 'سهم اتحادیه\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Quota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='به\u200cروزرسانی')),
                ('tracking_code', models.CharField(max_length=12, unique=True, verbose_name='کد رهگیری')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='مقدار سهمیه')),
                ('received_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='مقدار تحویل\u200cشده')),
                ('sold_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='مقدار فروخته\u200cشده')),
                ('carrier', models.CharField(blank=True, max_length=150, verbose_name='حمل\u200cکننده/توزیع\u200cکننده')),
                ('status', models.CharField(choices=[('assigned', 'تخصیص داده شد'), ('dispatched', 'ارسال شد'), ('received', 'تحویل فروشگاه'), ('sold_out', 'فروش کامل'), ('canceled', 'لغو')], db_index=True, default='assigned', max_length=12, verbose_name='وضعیت')),
            ],
            options={
                'verbose_name': 'سهمیه فروشگاه',
                'verbose_name_plural': 'سهمیه فروشگاه\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuotaEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('assigned', 'تخصیص داده شد'), ('dispatched', 'ارسال شد'), ('received', 'تحویل فروشگاه'), ('sold_out', 'فروش کامل'), ('canceled', 'لغو')], max_length=12)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
