# Generated by Django 5.2.17 on 2026-09-24 21:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('distribution', '0001_initial'),
        ('observatory', '0001_initial'),
        ('orgs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='allocation',
            name='commodity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='observatory.commodity', verbose_name='کالا'),
        ),
        migrations.AddField(
            model_name='allocation',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='allocation',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='orgs.province', verbose_name='استان'),
        ),
        migrations.AddField(
            model_name='allocationshare',
            name='allocation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='distribution.allocation'),
        ),
        migrations.AddField(
            model_name='allocationshare',
            name='union',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocation_shares', to='orgs.union', verbose_name='اتحادیه'),
        ),
        migrations.AddField(
            model_name='quota',
            name='share',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotas', to='distribution.allocationshare'),
        ),
        migrations.AddField(
            model_name='quota',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotas', to='orgs.store', verbose_name='فروشگاه'),
        ),
        migrations.AddField(
            model_name='quotaevent',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quotaevent',
            name='quota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='distribution.quota'),
        ),
        migrations.AlterUniqueTogether(
            name='allocationshare',
            unique_together={('allocation', 'union')},
        ),
    ]
