# Generated by Django 5.2.17 on 2026-10-09 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='به\u200cروزرسانی')),
                ('first_name', models.CharField(max_length=60, verbose_name='نام')),
                ('last_name', models.CharField(max_length=60, verbose_name='نام خانوادگی')),
                ('mobile', models.CharField(db_index=True, max_length=11, verbose_name='شماره تماس')),
                ('product_type', models.CharField(max_length=200, verbose_name='نوع کالای قابل تامین')),
                ('is_reviewed', models.BooleanField(default=False, verbose_name='بررسی شده')),
            ],
            options={
                'verbose_name': 'تامین\u200cکننده',
                'verbose_name_plural': 'تامین\u200cکنندگان',
                'ordering': ['-created_at'],
            },
        ),
    ]
