# Generated by Django 5.2.17 on 2026-10-07 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'مدیر کل سامانه'), ('governorate', 'استانداری'), ('samt', 'اداره صمت'), ('chamber', 'اتاق اصناف'), ('union', 'اتحادیه'), ('store', 'فروشگاه'), ('citizen', 'شهروند')], db_index=True, default='citizen', max_length=20, verbose_name='نقش'),
        ),
    ]
