# Generated by Django 5.2.17 on 2026-09-24 21:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orgs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='به\u200cروزرسانی')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='عنوان')),
                ('icon', models.CharField(blank=True, max_length=40, verbose_name='آیکن')),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cها',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OfferLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveBigIntegerField()),
                ('official_price', models.PositiveBigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='به\u200cروزرسانی')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='امتیاز')),
                ('comment', models.CharField(blank=True, max_length=500, verbose_name='نظر')),
                ('is_visible', models.BooleanField(default=True, verbose_name='نمایش')),
            ],
            options={
                'verbose_name': 'نظر',
                'verbose_name_plural': 'نظرات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoreOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='به\u200cروزرسانی')),
                ('price', models.PositiveBigIntegerField(verbose_name='قیمت فروشگاه (ریال)')),
                ('is_available', models.BooleanField(default=True, verbose_name='موجود')),
                ('confirmed_at', models.DateTimeField(db_index=True, verbose_name='آخرین تایید قیمت')),
            ],
            options={
                'verbose_name': 'قیمت فروشگاه',
                'verbose_name_plural': 'قیمت\u200cهای فروشگاه\u200cها',
            },
        ),
        migrations.CreateModel(
            name='DailySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('official_price', models.PositiveBigIntegerField()),
                ('min_price', models.PositiveBigIntegerField(null=True)),
                ('avg_price', models.PositiveBigIntegerField(null=True)),
                ('max_price', models.PositiveBigIntegerField(null=True)),
                ('offer_count', models.PositiveIntegerField(default=0)),
                ('stale_count', models.PositiveIntegerField(default=0)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='orgs.county')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='OfficialPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='نرخ (ریال)')),
                ('previous_price', models.PositiveBigIntegerField(default=0)),
                ('max_discount_percent', models.PositiveSmallIntegerField(default=20)),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='توضیح')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('set_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'نرخ مصوب',
                'verbose_name_plural': 'تاریخچه نرخ\u200cهای مصوب',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='به\u200cروزرسانی')),
                ('name', models.CharField(max_length=200, verbose_name='نام کالا')),
                ('unit', models.CharField(choices=[('kg', 'کیلوگرم'), ('g', 'گرم'), ('piece', 'عدد'), ('pack', 'بسته'), ('l', 'لیتر'), ('carton', 'کارتن')], default='kg', max_length=10, verbose_name='واحد')),
                ('unit_amount', models.DecimalField(decimal_places=3, default=1, max_digits=10, verbose_name='مقدار واحد')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('image', models.ImageField(blank=True, upload_to='products/', verbose_name='تصویر')),
                ('current_price', models.PositiveBigIntegerField(default=0, verbose_name='نرخ مصوب (ریال)')),
                ('max_discount_percent', models.PositiveSmallIntegerField(default=20, validators=[django.core.validators.MaxValueValidator(90)], verbose_name='حداکثر تخفیف مجاز (%)')),
                ('price_changed_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='زمان آخرین تغییر نرخ')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='market.category', verbose_name='دسته')),
            ],
            options={
                'verbose_name': 'کالا',
                'verbose_name_plural': 'کالاها',
                'ordering': ['name'],
            },
        ),
    ]
