# Generated by Django 5.2.17 on 2026-09-24 21:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market', '0001_initial'),
        ('observatory', '0001_initial'),
        ('orgs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='commodity',
            field=models.ForeignKey(blank=True, help_text='برای رصد قیمت کالاهای اساسی و سبد خانوار', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='observatory.commodity', verbose_name='کالای اساسی مرتبط'),
        ),
        migrations.AddField(
            model_name='product',
            name='union',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='orgs.union', verbose_name='اتحادیه'),
        ),
        migrations.AddField(
            model_name='officialprice',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='market.product'),
        ),
        migrations.AddField(
            model_name='dailysnapshot',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='market.product'),
        ),
        migrations.AddField(
            model_name='review',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='orgs.store'),
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='storeoffer',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='market.product', verbose_name='کالا'),
        ),
        migrations.AddField(
            model_name='storeoffer',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='orgs.store', verbose_name='فروشگاه'),
        ),
        migrations.AddField(
            model_name='offerlog',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='market.storeoffer'),
        ),
        migrations.AlterUniqueTogether(
            name='dailysnapshot',
            unique_together={('date', 'product', 'county')},
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('store', 'user')},
        ),
        migrations.AddIndex(
            model_name='storeoffer',
            index=models.Index(fields=['product', 'price'], name='market_stor_product_0570b5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='storeoffer',
            unique_together={('store', 'product')},
        ),
    ]
