# Generated by Django 5.2.17 on 2026-09-24 21:44

import apps.market.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='max_discount_percent',
            field=models.PositiveSmallIntegerField(default=apps.market.models.default_max_discount, validators=[django.core.validators.MaxValueValidator(90)], verbose_name='حداکثر تخفیف مجاز (%)'),
        ),
    ]
