# Generated by Django 5.2.17 on 2026-10-07 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_discount_default'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='officialprice',
            name='review_note',
            field=models.CharField(blank=True, max_length=300, verbose_name='توضیح بررسی'),
        ),
        migrations.AddField(
            model_name='officialprice',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان بررسی'),
        ),
        migrations.AddField(
            model_name='officialprice',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='بررسی\u200cکننده'),
        ),
        migrations.AddField(
            model_name='officialprice',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار تایید'), ('approved', 'تاییدشده'), ('rejected', 'رد شده')], db_index=True, default='approved', max_length=10, verbose_name='وضعیت'),
        ),
    ]
