# Generated by Django 5.2.17 on 2026-10-09 16:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='به\u200cروزرسانی')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان خبر')),
                ('image', models.ImageField(blank=True, upload_to='news/', verbose_name='عکس خبر')),
                ('body', models.TextField(verbose_name='متن خبر')),
                ('is_published', models.BooleanField(db_index=True, default=True, verbose_name='منتشر شود')),
                ('published_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='زمان انتشار')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده')),
            ],
            options={
                'verbose_name': 'خبر',
                'verbose_name_plural': 'اخبار',
                'ordering': ['-published_at'],
            },
        ),
    ]
