# Generated by Django 5.2.17 on 2026-09-24 21:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='به\u200cروزرسانی')),
                ('name', models.CharField(max_length=80, verbose_name='نام شهرستان')),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('population', models.PositiveIntegerField(blank=True, null=True, verbose_name='جمعیت')),
            ],
            options={
                'verbose_name': 'شهرستان',
                'verbose_name_plural': 'شهرستان\u200cها',
                'ordering': ['province__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='به\u200cروزرسانی')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='نام استان')),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'استان',
                'verbose_name_plural': 'استان\u200cها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Chamber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='به\u200cروزرسانی')),
                ('name', models.CharField(max_length=150, verbose_name='عنوان')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='نشانی')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='تلفن')),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chambers', to='orgs.county', verbose_name='شهرستان')),
            ],
            options={
                'verbose_name': 'اتاق اصناف',
                'verbose_name_plural': 'اتاق\u200cهای اصناف',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='county',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='counties', to='orgs.province', verbose_name='استان'),
        ),
        migrations.CreateModel(
            name='Union',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='به\u200cروزرسانی')),
                ('name', models.CharField(max_length=150, verbose_name='عنوان')),
                ('guild', models.CharField(blank=True, max_length=100, verbose_name='رسته صنفی')),
                ('logo', models.ImageField(blank=True, upload_to='unions/', verbose_name='لوگو')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='نشانی')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='تلفن')),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('chamber', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unions', to='orgs.chamber', verbose_name='اتاق اصناف')),
            ],
            options={
                'verbose_name': 'اتحادیه',
                'verbose_name_plural': 'اتحادیه\u200cها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='به\u200cروزرسانی')),
                ('name', models.CharField(max_length=150, verbose_name='نام فروشگاه')),
                ('license_no', models.CharField(blank=True, max_length=50, verbose_name='شماره پروانه کسب')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='تلفن')),
                ('address', models.CharField(max_length=300, verbose_name='نشانی')),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('working_hours', models.CharField(blank=True, max_length=100, verbose_name='ساعات کاری')),
                ('photo', models.ImageField(blank=True, upload_to='stores/', verbose_name='تصویر')),
                ('license_image', models.ImageField(blank=True, upload_to='stores/licenses/', verbose_name='تصویر پروانه')),
                ('status', models.CharField(choices=[('pending', 'در انتظار تایید'), ('active', 'فعال'), ('rejected', 'رد شده'), ('suspended', 'تعلیق')], db_index=True, default='pending', max_length=12, verbose_name='وضعیت')),
                ('status_reason', models.TextField(blank=True, verbose_name='دلیل رد/تعلیق')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False, help_text='احراز هویت کامل توسط اتحادیه', verbose_name='نشان اعتماد')),
                ('rating_avg', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('rating_count', models.PositiveIntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stores', to=settings.AUTH_USER_MODEL, verbose_name='مالک')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('union', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stores', to='orgs.union', verbose_name='اتحادیه')),
            ],
            options={
                'verbose_name': 'فروشگاه',
                'verbose_name_plural': 'فروشگاه\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='county',
            unique_together={('province', 'name')},
        ),
    ]
