# Generated by Django 5.2.17 on 2026-10-09 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='covered_unions',
            field=models.ManyToManyField(blank=True, help_text='برای فروشگاه فاقد اتحادیه: کالاهای کدام اتحادیه\u200cهایی را عرضه می\u200cکند', related_name='covered_stores', to='orgs.union', verbose_name='اتحادیه\u200cهای تحت پوشش'),
        ),
        migrations.AlterField(
            model_name='store',
            name='union',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stores', to='orgs.union', verbose_name='اتحادیه'),
        ),
    ]
