# Generated by Django 5.2.17 on 2026-09-24 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orgs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('new', 'ثبت شده'), ('reviewing', 'در حال بررسی'), ('inspection', 'ارجاع به بازرسی'), ('resolved', 'رسیدگی شد'), ('rejected', 'رد شد')], max_length=12)),
                ('note', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=True, verbose_name='قابل مشاهده برای شهروند')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='به\u200cروزرسانی')),
                ('tracking_code', models.CharField(max_length=12, unique=True, verbose_name='کد رهگیری')),
                ('reporter_name', models.CharField(max_length=120, verbose_name='نام گزارش\u200cدهنده')),
                ('kind', models.CharField(choices=[('overprice', 'گران\u200cفروشی'), ('not_honored', 'عدم رعایت قیمت اعلام\u200cشده'), ('unavailable', 'عدم عرضه با وجود اعلام موجودی'), ('quality', 'کیفیت نامناسب'), ('weight', 'کم\u200cفروشی'), ('other', 'سایر')], default='overprice', max_length=20, verbose_name='نوع تخلف')),
                ('shop_name', models.CharField(blank=True, max_length=150, verbose_name='نام فروشگاه')),
                ('shop_address', models.CharField(blank=True, max_length=300, verbose_name='نشانی فروشگاه')),
                ('announced_price', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='قیمت اعلامی فروشگاه')),
                ('official_price', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='نرخ مصوب')),
                ('paid_price', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='قیمت دریافتی')),
                ('description', models.TextField(verbose_name='شرح')),
                ('attachment', models.FileField(blank=True, upload_to='complaints/%Y/%m/', verbose_name='تصویر فاکتور/مستند')),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('status', models.CharField(choices=[('new', 'ثبت شده'), ('reviewing', 'در حال بررسی'), ('inspection', 'ارجاع به بازرسی'), ('resolved', 'رسیدگی شد'), ('rejected', 'رد شد')], db_index=True, default='new', max_length=12, verbose_name='وضعیت')),
                ('violation_confirmed', models.BooleanField(blank=True, null=True, verbose_name='تخلف محرز شد')),
                ('resolution', models.TextField(blank=True, verbose_name='نتیجه رسیدگی')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('chamber_seen_at', models.DateTimeField(blank=True, null=True)),
                ('chamber', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='complaints', to='orgs.chamber')),
            ],
            options={
                'verbose_name': 'شکایت',
                'verbose_name_plural': 'شکایات',
                'ordering': ['-created_at'],
            },
        ),
    ]
