# Generated by Django 5.2.17 on 2026-09-24 21:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market', '0001_initial'),
        ('orgs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='به\u200cروزرسانی')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='نام کالا')),
                ('group', models.CharField(choices=[('protein', 'پروتئینی'), ('dairy', 'لبنیات'), ('grain', 'غلات و حبوبات'), ('oil_sugar', 'روغن، قند و شکر'), ('produce', 'صیفی و تره\u200cبار'), ('hygiene', 'بهداشتی و شوینده'), ('feed', 'نهاده دامی'), ('other', 'سایر')], default='other', max_length=12, verbose_name='گروه')),
                ('unit', models.CharField(default='کیلوگرم', max_length=20, verbose_name='واحد')),
                ('subsidized', models.BooleanField(default=False, verbose_name='وارداتی با ارز دولتی/یارانه\u200cای')),
                ('basket_monthly_qty', models.DecimalField(decimal_places=2, default=0, help_text='صفر یعنی در سبد خانوار محاسبه نمی\u200cشود', max_digits=8, verbose_name='مقدار ماهانه در سبد خانوار')),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'کالای اساسی',
                'verbose_name_plural': 'کالاهای اساسی',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('official_jump', 'جهش نرخ مصوب'), ('market_jump', 'جهش قیمت بازار'), ('shortage', 'کاهش عرضه'), ('stale', 'عدم به\u200cروزرسانی قیمت'), ('complaints', 'افزایش شکایات')], max_length=16)),
                ('level', models.CharField(choices=[('info', 'اطلاع'), ('warning', 'هشدار'), ('critical', 'بحرانی')], default='warning', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField(blank=True)),
                ('change_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('is_resolved', models.BooleanField(db_index=True, default=False)),
                ('dedupe_key', models.CharField(blank=True, db_index=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('county', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='orgs.county')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='market.product')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='orgs.store')),
            ],
            options={
                'verbose_name': 'هشدار',
                'verbose_name_plural': 'هشدارها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommodityReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='به\u200cروزرسانی')),
                ('period', models.DateField(db_index=True, verbose_name='تاریخ دوره')),
                ('annual_need_kt', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='نیاز سالانه (هزار تن)')),
                ('annual_production_kt', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='تولید سالانه (هزار تن)')),
                ('imports_kt', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='واردات (هزار تن)')),
                ('import_price', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='قیمت واردات (ریال/کیلو)')),
                ('clearance_cost', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='هزینه ترخیص و حمل (ریال/کیلو)')),
                ('neighbor_price_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='قیمت در کشور همسایه (دلار/کیلو)')),
                ('neighbor_country', models.CharField(blank=True, default='عراق', max_length=40, verbose_name='کشور همسایه')),
                ('per_capita_stat', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='سرانه مصرف طبق آمار (کیلو)')),
                ('producer_price', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='قیمت تولیدکننده/سر مزرعه/زنده')),
                ('wholesale_price', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='قیمت عمده/کشتارگاه')),
                ('consumer_price_county', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='قیمت مصرف\u200cکننده در شهرستان')),
                ('consumer_price_center', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='قیمت مصرف\u200cکننده در مرکز استان')),
                ('consumer_price_tehran', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='قیمت مصرف\u200cکننده در تهران')),
                ('national_min', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='ارزان\u200cترین قیمت استان\u200cها')),
                ('national_max', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='گران\u200cترین قیمت استان\u200cها')),
                ('national_avg', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='متوسط قیمت کشور')),
                ('source', models.CharField(blank=True, max_length=200, verbose_name='منبع')),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='observatory.commodity')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('province', models.ForeignKey(blank=True, help_text='خالی = گزارش ملی', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commodity_reports', to='orgs.province')),
            ],
            options={
                'verbose_name': 'گزارش تامین و قیمت',
                'verbose_name_plural': 'گزارش\u200cهای تامین و قیمت',
                'ordering': ['-period', 'commodity__order'],
                'unique_together': {('commodity', 'province', 'period')},
            },
        ),
    ]
